/**
 * Bounding box returned by Gemini.
 *
 * Gemini coordinates are normalized to 0–1000.
 *
 * Origin:
 * top-left
 *
 * Example:
 *
 * xmin = 100
 * ymin = 200
 * xmax = 850
 * ymax = 300
 */
export interface AnswerBox {
  ymin: number;
  xmin: number;
  ymax: number;
  xmax: number;
}

/**
 * A region belonging to one answer.
 *
 * An answer can have multiple regions when
 * it spans multiple pages.
 */
export interface AnswerRegion {
  /**
   * 1-based PDF page number.
   */
  page: number;

  /**
   * Gemini normalized bounding box.
   */
  box: AnswerBox;
}

/**
 * Extracted student answer.
 */
export interface ExtractedAnswer {
  /**
   * Question label detected on answer sheet.
   *
   * Empty string means no label was detected.
   */
  questionNumber: string;

  /**
   * OCR / handwriting extraction result.
   */
  answerText: string;

  /**
   * One or more regions containing the answer.
   */
  regions: AnswerRegion[];
}

/**
 * Extracted question.
 */
export interface ExtractedQuestion {
  number: string;

  text: string;

  /**
   * Page where the question starts.
   */
  page: number;

  type: "main" | "subpart";
}

/**
 * How the answer was mapped.
 */
export type MatchType =
  | "explicit"
  | "semantic";

/**
 * Final mapping generated by Phase 5.
 */
export interface QuestionAnswerMapping {
  questionNumber: string;

  questionText: string;

  status:
    | "answered"
    | "unanswered";

  matchType:
    | MatchType
    | null;

  confidence: number;

  /**
   * Index of the corresponding answer.
   */
  answerIndex: number | null;
}

/**
 * Unmatched answer returned by Phase 5.
 */
export interface UnmatchedAnswer {
  answerIndex: number;

  questionNumber: string;

  answerText: string;

  reason: string;
}

/**
 * Complete Phase 5 mapping response.
 */
export interface MappingResult {
  mappings: QuestionAnswerMapping[];

  unmatchedAnswers: UnmatchedAnswer[];

  summary: {
    totalQuestions: number;

    answeredQuestions: number;

    unansweredQuestions: number;

    totalAnswers: number;

    unmatchedAnswers: number;
  };
}

/**
 * Complete assessment data used by Phase 6.
 */
export interface AssessmentData {
  /**
   * Original question paper PDF.
   *
   * This is used by react-pdf.
   */
  questionPaper: File;

  /**
   * Original student answer sheet.
   *
   * This is the PDF we display in Phase 6.
   */
  answerSheet: File;

  /**
   * Extracted questions.
   */
  questions: ExtractedQuestion[];

  /**
   * Extracted answers.
   */
  answers: ExtractedAnswer[];

  /**
   * Phase 5 mapping.
   */
  mapping: MappingResult;
}